module.exports = {
  content: ["./docs/**/*.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#ceceff",
        "background": "#f0f2f5",
        "on-primary-fixed-variant": "#3c3d8e",
        "tertiary-fixed": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#eceef1",
        "surface-dim": "#d8dadd",
        "primary-container": "#5051a3",
        "on-secondary": "#ffffff",
        "surface-variant": "#e0e3e6",
        "on-tertiary-fixed-variant": "#93000f",
        "on-surface-variant": "#464651",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#410003",
        "tertiary-container": "#b4121b",
        "surface-container-highest": "#e0e3e6",
        "on-secondary-fixed-variant": "#504700",
        "error": "#ba1a1a",
        "on-tertiary-container": "#ffc4be",
        "secondary-container": "#fbe437",
        "on-background": "#191c1e",
        "on-secondary-fixed": "#201c00",
        "surface": "#f0f2f5",
        "surface-container-low": "#f2f4f7",
        "inverse-surface": "#2d3133",
        "tertiary": "#8b000e",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "outline": "#777682",
        "error-container": "#ffdad6",
        "surface-tint": "#5455a8",
        "secondary-fixed-dim": "#dec811",
        "primary-fixed": "#e1dfff",
        "on-secondary-container": "#716500",
        "on-primary-fixed": "#0d0763",
        "secondary-fixed": "#fbe437",
        "secondary": "#6a5f00",
        "tertiary-fixed-dim": "#ffb3ac",
        "outline-variant": "#c7c5d3",
        "on-surface": "#191c1e",
        "primary": "#38398a",
        "inverse-on-surface": "#eff1f4",
        "surface-bright": "#f7f9fc",
        "surface-container-high": "#e6e8eb",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#c1c1ff",
        "primary-fixed-dim": "#c1c1ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "card-padding": "1.25rem",
        "stack-sm": "0.5rem",
        "stack-lg": "2rem",
        "stack-md": "1rem",
        "gutter-grid": "1rem",
        "margin-page": "1.5rem"
      },
      fontFamily: {
        "headline-md": ["Hanken Grotesk"],
        "id-name": ["Hanken Grotesk"],
        "label-caps": ["Hanken Grotesk"],
        "id-data": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"]
      },
      fontSize: {
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "id-name": ["20px", { "lineHeight": "24px", "letterSpacing": "0.01em", "fontWeight": "700" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.08em", "fontWeight": "800" }],
        "id-data": ["18px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
